name: "Auto-bisect Action"
description: "An action to automatically perform a git-bisect between two commits"
inputs:
  bad-commit:
    description: The branch or commit contains the issue
    type: string
    required: true
  good-commit:
    description: The origin branch or commit, that does not contain the issue
    type: string
    required: true
  bisect-comand:
    description: The command to run to test the source code
    type: string
    required: true
  shell:
    description: The shell to use
    type: string
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Bisect changes from ${{ inputs.good-commit }} to ${{ inputs.bad-commit }}
      shell: ${{ inputs.shell }}
      run: |
        git fetch origin
        good_commit=$(git rev-parse origin/${{ inputs.good-commit }})
        bad_commit=$(git rev-parse origin/${{ inputs.bad-commit }})
        git bisect start $bad_commit $good_commit --
        git bisect run ${{ inputs.bisect-comand }}
        git bisect reset
branding:
  icon: "git-commit"
  color: "green"
